version: "3.9"

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: ocr-ragsystem-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ocr_user
      POSTGRES_PASSWORD: ocr_pass
      POSTGRES_DB: ocr_rag_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
